### ISSUE TITLE
Add association to lambda function

### ISSUE THREAD

**Issue by chantzlarge** [chantzlarge/terraform-aws-hugo#3]
Hugo build output creates directory indexes (index.html) that are unsupported by CloudFront. To support navigation, the request must be intervened and redirected to the directory index file. This is possible using Lambda@Edge functions. Most of this is already implemented, however to complete, a function association must be made between the CloudFront resource and the Lambda function by adding the following property to the CloudFront resource definition:

[https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#lambda-function-association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#lambda-function-association)

**Comment by 0xlarge** [comment]
While researching how to implement this with Terraform, I discovered another way of implementing this using AWS CloudFront Functions; a new(er) feature I've been unaware of. See:

- [https://aws.amazon.com/blogs/aws/introducing-cloudfront-functions-run-your-code-at-the-edge-with-low-latency-at-any-scale/](https://aws.amazon.com/blogs/aws/introducing-cloudfront-functions-run-your-code-at-the-edge-with-low-latency-at-any-scale/)
